version: '3.5'
services:
  app:
      image: live-coding
      build:
        context: .
        dockerfile: Dockerfile
      links: [db, testdb]
      volumes:
        - web_app:/var/www/html
      environment:
        - "DB_PORT=3306"
        - "DB_HOST=db"
        - "DB_DATABASE=homestead"
        - "DB_USERNAME=homestead"
        - "DB_PASSWORD=secret"
  web:
      image: nginx:latest
      links: ["app:php"]
      volumes:
        - web_app:/var/www/html
        - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      ports: ["8099:80"]
  db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD : secret
        MYSQL_DATABASE : homestead
        MYSQL_USER : homestead
        MYSQL_PASSWORD : secret
      volumes:
        - ./dbdata/:/var/lib/mysql
      ports: ["33063:3306"]

  testdb:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD : secret
        MYSQL_DATABASE : homestead
        MYSQL_USER : homestead
        MYSQL_PASSWORD : secret
      # ports: ["33063:"]

volumes:
  web_app:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind